export const products = [
  // Round Plates
  {
    id: "6-inch-round-plate",
    name: "6 Inch Round Plate",
    category: "round-plates",
    description: "6-Inch Round Bagasse Plates Made from 100% biodegradable and compostable sugarcane fibers, these sturdy plates are eco-friendly and durable. They are perfect for serving snacks, desserts, and appetizers. Microwave and freezer safe, they are ideal for both hot and cold foods. A sustainable, guilt-free alternative to plastic or paper plates!",
    material: "Sugarcane Bagasse",
    images: [
      "/products/round_plate/common.jpg",
      "/products/round_plate/6_ rp/1.jpg",
      "/products/round_plate/6_ rp/2.jpg",
    ],
    specs: {
      size: 'Ø6" x H 0.4" Inch \nØ152 x H 10 MM',
      weight: "6 gm",
      pcsInPack: "50 PC",
      packInCarton: "20 Pack",
      totalPcsInCarton: "1000 PCS",
      boxDimension: "12.60 x 12.60 x 11.42 (Inch) \n320 x 320 x 290 (MM)",
      boxCBM: "0.0297",
    },
  },
  {
    id: "7-inch-round-plate",
    name: "7 Inch Round Plate",
    category: "round-plates",
    description: "7-Inch Round Bagasse Plates Made from 100% biodegradable and compostable sugarcane fibers, these sturdy plates are eco-friendly and durable. Perfect for serving main courses and larger portions. Microwave and freezer safe, ideal for both hot and cold foods.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/round_plate/common.jpg",
      "/products/round_plate/7_rp/1.jpg",
      "/products/round_plate/7_rp/2.jpg",
    ],
    specs: {
      size: 'Ø7" x H 0.8" Inch \nØ175 x H 19.5 MM',
      weight: "8 gm",
      pcsInPack: "50 PC",
      packInCarton: "20 Pack",
      totalPcsInCarton: "1000 PCS",
      boxDimension: "14.76 x 14.76 x 10.24 (Inch) \n375 x 375 x 260 (MM)",
      boxCBM: "0.0366",
    },
  },
  {
    id: "9-inch-round-plate",
    name: "9 Inch Round Plate",
    category: "round-plates",
    description: "9-Inch Round Bagasse Plates Made from 100% biodegradable and compostable sugarcane fibers. Sturdy and durable for hearty meals. Microwave and freezer safe, perfect for both hot and cold foods.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/round_plate/common.jpg",
      "/products/round_plate/9_rp/1.jpg",
      "/products/round_plate/9_rp/2.jpg",
    ],
    specs: {
      size: 'Ø9" x H 0.7" Inch \nØ225 x H 18 MM',
      weight: "14 gm",
      pcsInPack: "50 PC",
      packInCarton: "10 Pack",
      totalPcsInCarton: "500 PCS",
      boxDimension: "18.11 x 9.84 x 12.20 (Inch) \n460 x 250 x 310 (MM)",
      boxCBM: "0.0357",
    },
  },
  {
    id: "10-inch-round-plate",
    name: "10 Inch Round Plate",
    category: "round-plates",
    description: "10-Inch Round Bagasse Plates Made from 100% biodegradable and compostable sugarcane fibers. Large surface area perfect for full meals. Microwave and freezer safe, ideal for both hot and cold foods.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/round_plate/common.jpg",
      "/products/round_plate/10_rp/1.jpg",
      "/products/round_plate/10_rp/2.jpg",
    ],
    specs: {
      size: 'Ø10" x H 0.7" Inch \nØ250 x H 18 MM',
      weight: "18 gm",
      pcsInPack: "50 PC",
      packInCarton: "10 Pack",
      totalPcsInCarton: "500 PCS",
      boxDimension: "20.47 x 10.63 x 12.20 (Inch) \n520 x 270 x 310 (MM)",
      boxCBM: "0.0435",
    },
  },
  {
    id: "12-inch-round-plate",
    name: "12 Inch Round Plate",
    category: "round-plates",
    description: "12-Inch Round Bagasse Plates Made from 100% biodegradable and compostable sugarcane fibers. Extra large size for generous portions. Microwave and freezer safe, ideal for both hot and cold foods.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/round_plate/common.jpg",
      "/products/round_plate/12_rp/1.jpg",
      "/products/round_plate/12_rp/2.jpg",
    ],
    specs: {
      size: 'Ø12" x H 0.9" Inch \nØ302 x H 24 MM',
      weight: "25 gm",
      pcsInPack: "50 PC",
      packInCarton: "8 Pack",
      totalPcsInCarton: "400 PCS",
      boxDimension: "24.41 x 12.20 x 12.80 (Inch) \n620 x 310 x 325 (MM)",
      boxCBM: "0.0625",
    },
  },

  // Meal Trays
  {
    id: "9-inch-3-compartment-plate",
    name: "9 Inch 3 Compartment Plate",
    category: "meal-trays",
    description: "9-Inch 3 Compartment Bagasse Plate Made from 100% biodegradable and compostable sugarcane fibers. Perfect for separating different food items. Microwave and freezer safe, ideal for both hot and cold foods.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/meal_tray/9_3cm/1.jpg",
      "/products/meal_tray/9_3cm/2.jpg",
      "/products/meal_tray/9_3cm/3.jpg",
    ],
    specs: {
      size: '9" x ?" x H 0.8" Inch \n225 x ? x H 20 MM',
      weight: "14 gm",
      pcsInPack: "50 PC",
      packInCarton: "10 Pack",
      totalPcsInCarton: "500 PCS",
      boxDimension: "18.11 x 9.06 x 12.01 (Inch) \n460 x 230 x 305 (MM)",
      boxCBM: "0.0323",
    },
  },
  {
    id: "10-inch-3-compartment-plate",
    name: "10 Inch 3 Compartment Plate",
    category: "meal-trays",
    description: "10-Inch 3 Compartment Bagasse Plate Made from 100% biodegradable and compostable sugarcane fibers. Spacious sections for a complete meal. Microwave and freezer safe, ideal for both hot and cold foods.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/meal_tray/10_3cm/1.jpg",
      "/products/meal_tray/10_3cm/2.jpg",
    ],
    specs: {
      size: '10" x ?" x H 0.7" Inch \n250 x ? x H 19 MM',
      weight: "20 gm",
      pcsInPack: "50 PC",
      packInCarton: "10 Pack",
      totalPcsInCarton: "500 PCS",
      boxDimension: "20.47 x 10.63 x 12.40 (Inch) \n520 x 270 x 315 (MM)",
      boxCBM: "0.0442",
    },
  },
  {
    id: "3-cp-meal-tray",
    name: "3 Compartment Meal Tray",
    category: "meal-trays",
    description: "3 Compartment Meal Tray Made from 100% biodegradable and compostable sugarcane fibers. Perfect for balanced meals with separate sections. Microwave and freezer safe, ideal for both hot and cold foods.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/meal_tray/3cm MT/1.jpg",
      "/products/meal_tray/3cm MT/2.jpg",
      "/products/meal_tray/3cm MT/3.jpg",
    ],
    specs: {
      size: '8.5" x 8.5" x H 0.9" Inch \n215 x 215 x H 24 MM',
      weight: "19 gm",
      pcsInPack: "50 PC",
      packInCarton: "10 Pack",
      totalPcsInCarton: "500 PCS",
      boxDimension: "18.11 x 9.84 x 13.00 (Inch) \n460 x 250 x 330 (MM)",
      boxCBM: "0.0380",
    },
  },
  {
    id: "5-cp-meal-tray",
    name: "5 Compartment Meal Tray",
    category: "meal-trays",
    description: "5 Compartment Meal Tray Made from 100% biodegradable and compostable sugarcane fibers. Multiple sections for diverse meals. Microwave and freezer safe, ideal for both hot and cold foods.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/meal_tray/5cm MT/1.jpg",
      "/products/meal_tray/5cm MT/2.jpg",
      "/products/meal_tray/5cm MT/3.jpg",
    ],
    specs: {
      size: '11.1" x 8.7" x H 1.2" Inch \n282 x 220 x H 30 MM',
      weight: "32 gm",
      pcsInPack: "50 PC",
      packInCarton: "8 Pack",
      totalPcsInCarton: "400 PCS",
      boxDimension: "17.72 x 11.22 x 15.75 (Inch) \n450 x 285 x 400 (MM)",
      boxCBM: "0.0513",
    },
  },
  {
    id: "6-cp-meal-tray",
    name: "6 Compartment Meal Tray",
    category: "meal-trays",
    description: "6 Compartment Meal Tray Made from 100% biodegradable and compostable sugarcane fibers. Perfect for multi-item meals. Microwave and freezer safe, ideal for both hot and cold foods.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/meal_tray/6cm MT/1.jpg",
      "/products/meal_tray/6cm MT/2.jpg",
      "/products/meal_tray/6cm MT/3.jpg",
    ],
    specs: {
      size: '12.0" x 9.0" x H 1.3" Inch \n304 x 228 x H 33 MM',
      weight: "38 gm",
      pcsInPack: "50 PC",
      packInCarton: "6 Pack",
      totalPcsInCarton: "300 PCS",
      boxDimension: "18.50 x 12.40 x 13.78 (Inch) \n470 x 315 x 350 (MM)",
      boxCBM: "0.0518",
    },
  },

  // Bowls
  {
    id: "180ml-bowl",
    name: "180 ml Bowl",
    category: "bowls",
    description: "180 ml Bowl Made from 100% biodegradable and compostable sugarcane fibers. Perfect for small portions, dips, and sides. Microwave and freezer safe, ideal for both hot and cold foods.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/bowls/180ml bowl/1.jpg",
      "/products/bowls/180ml bowl/2.jpg",
      "/products/bowls/180ml bowl/3.jpg",
    ],
    specs: {
      size: 'Ø4.3" x H 1.5" Inch \nØ108 x H 37 MM',
      weight: "5 gm",
      pcsInPack: "50 PC",
      packInCarton: "20 Pack",
      totalPcsInCarton: "1000 PCS",
      boxDimension: "21.26 x 8.66 x 9.06 (Inch) \n540 x 220 x 230 (MM)",
      boxCBM: "0.0273",
    },
  },
  {
    id: "240ml-bowl",
    name: "240 ml Bowl",
    category: "bowls",
    description: "240 ml Bowl Made from 100% biodegradable and compostable sugarcane fibers. Ideal for soups, cereals, and desserts. Microwave and freezer safe, perfect for both hot and cold foods.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/bowls/240ml bowl/1.jpg",
      "/products/bowls/240ml bowl/2.jpg",
      "/products/bowls/240ml bowl/3.jpg",
    ],
    specs: {
      size: 'Ø4.6" x H 1.5" Inch \nØ118 x H 38 MM',
      weight: "7 gm",
      pcsInPack: "50 PC",
      packInCarton: "20 Pack",
      totalPcsInCarton: "1000 PCS",
      boxDimension: "275 x 275 x 433 (MM)",
      boxCBM: "0.0327",
    },
  },
  {
    id: "12oz-bowl-360ml",
    name: "12 oz Bowl (360 ml)",
    category: "bowls",
    description: "12 oz (360 ml) Bowl Made from 100% biodegradable and compostable sugarcane fibers. Perfect for larger portions of soup, salad, or snacks. Microwave and freezer safe, ideal for both hot and cold foods.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/bowls/12oz 360ml/1.jpg",
      "/products/bowls/12oz 360ml/2.jpg",
      "/products/bowls/12oz 360ml/3.jpg",
    ],
    specs: {
      size: 'Ø5.9" x H 1.6" Inch \nØ150 x H 40 MM',
      weight: "9 gm",
      pcsInPack: "50 PC",
      packInCarton: "20 Pack",
      totalPcsInCarton: "1000 PCS",
      boxDimension: "13.00 x 13.00 x 18.11 (Inch) \n330 x 330 x 460 (MM)",
      boxCBM: "0.0501",
    },
  },

  // Clamshells (Items 30-34)
  {
    id: "6x6-clamshell",
    name: "6 x 6 Clamshell",
    category: "clamshells",
    description: "6 x 6 Inch Clamshell Box Made from 100% biodegradable and compostable sugarcane fibers. Perfect for sandwiches, burgers, and takeaway meals. Secure locking mechanism, microwave safe.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/clamshell/6_6/1.jpg",
      "/products/clamshell/6_6/2.jpg",
      "/products/clamshell/6_6/3.jpg",
    ],
    specs: {
      size: '6" x 6" x H 1.7" Inch \n153 x 153 x H 42 MM',
      weight: "21 gm",
      pcsInPack: "50 PC",
      packInCarton: "10 Pack",
      totalPcsInCarton: "500 PCS",
      boxDimension: "12.52 x 12.24 x 17.01 (Inch) \n318 x 311 x 432 (MM)",
      boxCBM: "0.0427",
    },
  },
  {
    id: "9x6-plain-clamshell",
    name: "9 x 6 Plain Clamshell",
    category: "clamshells",
    description: "9 x 6 Inch Plain Clamshell Box Made from 100% biodegradable and compostable sugarcane fibers. Ideal for larger sandwiches and meals. Secure locking mechanism, microwave safe.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/clamshell/9_6/1.jpg",
      "/products/clamshell/9_6/2.jpg",
      "/products/clamshell/9_6/3.jpg",
    ],
    specs: {
      size: '9.1" x 6.0" x H 1.7" Inch \n232 x 152 x H 42 MM',
      weight: "29 gm",
      pcsInPack: "50 PC",
      packInCarton: "5 Pack",
      totalPcsInCarton: "250 PCS",
      boxDimension: "12.24 x 9.25 x 17.01 (Inch) \n311 x 235 x 432 (MM)",
      boxCBM: "0.0316",
    },
  },

  {
    id: "9x9-plain-clamshell",
    name: "9 x 9 Plain Clamshell",
    category: "clamshells",
    description: "9 x 9 Inch Plain Clamshell Box Made from 100% biodegradable and compostable sugarcane fibers. Large square container for generous portions. Secure locking mechanism, microwave safe.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/clamshell/9_9/1.jpg",
      "/products/clamshell/9_9/2.jpg",
      "/products/clamshell/9_9/3.jpg",
    ],
    specs: {
      size: '9.3" x 9.1" x H 1.7" Inch \n235 x 230 x H 44 MM',
      weight: "44 gm",
      pcsInPack: "50 PC",
      packInCarton: "4 Pack",
      totalPcsInCarton: "200 PCS",
      boxDimension: "19.02 x 9.02 x 14.49 (Inch) \n483 x 229 x 368 (MM)",
      boxCBM: "0.0407",
    },
  },
  {
    id: "8x8-3cp-clamshell",
    name: "8 x 8 - 3 Compartment Clamshell",
    category: "clamshells",
    description: "8 x 8 Inch 3 Compartment Clamshell Box Made from 100% biodegradable and compostable sugarcane fibers. Features separated sections for a complete meal. Secure locking mechanism, microwave safe.",
    material: "Sugarcane Bagasse",
    images: [
      "/products/clamshell/8_8 3cp/1.jpg",
      "/products/clamshell/8_8 3cp/2.jpg",
      "/products/clamshell/8_8 3cp/3.jpg",
    ],
    specs: {
      size: '8.3" x 8.4" x H 2.0" Inch \n210 x 213 x H 51 MM',
      weight: "36 gm",
      pcsInPack: "50 PC",
      packInCarton: "4 Pack",
      totalPcsInCarton: "200 PCS",
      boxDimension: "19.02 x 15.51 x 19.02 (Inch) \n483 x 394 x 483 (MM)",
      boxCBM: "0.0919",
    },
  },
];

export const categories = [
  { name: "Round Plates", slug: "round-plates" },
  { name: "Bowls", slug: "bowls" },
  { name: "Meal Trays", slug: "meal-trays" },
  { name: "Clamshells", slug: "clamshells" },
];