import ProductsClient from "@/components/pages/products/ProductsClient";

export const metadata = {
  title: "Premium Sugarcane Bagasse Products | DineX Ecopack Sustainable Collection",
  description:
    "Explore our full range of eco-responsive tableware. From clamshells and plates to bowls and meal boxes, find the perfect sustainable packaging for your business.",
  keywords: [
    "Kraft Food Container Manufacturer",
    "Kraft Takeaway Bowl Supplier",
    "Kraft Soup Bowl Manufacturer",
    "Kraft Noodle Bowl Manufacturer",
    "Kraft Rice Bowl Supplier",
    "Kraft Food Packaging Manufacturer",
    "Kraft Container Exporter",
    "Paper Food Container Manufacturer",
    "Paper Takeaway Bowl Manufacturer",
    "Paper Meal Bowl Supplier",
    "Paper Packaging for Restaurants",
    "Paper Packaging for Cafes",
    "Paper Packaging for Food Delivery",
    "Salad Bowl Manufacturer",
    "Salad Bowl Exporter",
    "Salad Packaging Supplier",
    "Premium Salad Bowl Manufacturer",
    "Disposable Salad Packaging",
    "Takeaway Salad Packaging",
    "Healthy Food Packaging Solutions",
    "Fresh Food Packaging Supplier",
    "Ready To Eat Packaging",
    "Meal Prep Packaging Manufacturer",
    "Custom Printed Paper Bowl",
    "Custom Printed Food Container",
    "Custom Printed Packaging Manufacturer",
    "Branded Food Packaging Supplier",
    "OEM Food Packaging Supplier",
    "Custom Logo Food Packaging",
    "White Label Packaging Supplier",
    "White Paper Salad Bowl Manufacturer",
    "White Paper Bowl Supplier",
    "White Food Containers",
    "Premium Paper Bowls",
    "Paper Takeaway Containers",
    "Food Service Packaging",
    "Recyclable Salad Bowl Manufacturer",
    "Sustainable Salad Bowl Packaging",
    "Eco Friendly Food Bowl Supplier",
    "Alternative to Plastic Containers",
    "BRC Packaging Supplier",
    "FSC Packaging Manufacturer",
    "Food Contact Safe Packaging",
    "Export Quality Food Packaging",
    "Airline Food Packaging Supplier",
    "Supermarket Packaging Supplier",
    "Quick Service Restaurant Packaging",
    "Takeaway Packaging Exporter",
    "Custom Branding Packaging",
    "Retail Packaging Solutions",
    "Food Brand Packaging Partner",
    "Bulk Food Packaging",
  ],
};

export default function ProductsPage() {
  return <ProductsClient />;
}
